include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda


HEADERS=convec.h

OPS_FILES=convec.cpp

OPS_GENERATED=convec_ops.cpp

APP=convec
MAIN_SRC=convec.cpp

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.c_app
