include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda


HEADERS=time_marching_kernel.h

OPS_FILES=time_marching.cpp

OPS_GENERATED=time_marching_ops.cpp

APP=time_marching
MAIN_SRC=time_marching.cpp

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.c_app
